fix: Add torch.utils.data and torch.optim.Optimizer to FakeTorch
Extends FakeTorch to support more PyTorch APIs that are used in trainer code.

Changes:
- Add torch.utils.data.Dataset class
- Add torch.utils.data.DataLoader class
- Add torch.optim.Optimizer base class

Fixes AttributeError when importing trainer.py:
  - 'FakeTorch' object has no attribute 'utils'
  - type object 'optim' has no attribute 'Optimizer'

This allows code to use type annotations like:
  - torch.utils.data.Dataset
  - torch.optim.Optimizer

even when PyTorch is not installed (e.g., in CLI help mode).